version: '3'

services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/car_market_database
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: car_market_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - '5432:5432'
