version: '3.8'
services:
  auto-market-postgres:
    image: postgres:latest
    container_name: auto-market-postgres
    restart: on-failure
    environment:
      POSTGRES_DB: car_market_database
      POSTGRES_USER: car_market_admin
      POSTGRES_PASSWORD: car_market_admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5433'
    networks:
      - app_network

  auto-market-mongo:
    image: mongo:7.0
    restart: on-failure
    container_name: auto-market-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: car_market_admin
      MONGO_INITDB_ROOT_PASSWORD: car_market_admin
      MONGO_INITDB_DATABASE: car_market_db
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app_network

  auto-market-backend:
    build:
      context: ./back-end
    container_name: auto-market-backend
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - auto-market-postgres
      - auto-market-mongo
    # environment:
    #   SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/car_market_database
    #   SPRING_DATASOURCE_USERNAME: car_market_admin
    #   SPRING_DATASOURCE_PASSWORD: car_market_admin
    networks:
      - app_network

  auto-market-frontend:
    build:
      context: ./front-end
    container_name: auto-market-frontend
    restart: always
    ports:
      - '3000:3000'
    # depends_on:
      # - auto-market-backend
    networks:
      - app_network
      
networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data: