services:
  auto-market-postgres:
    image: postgres:latest
    container_name: auto-market-postgres
    restart: on-failure
    environment:
      POSTGRES_DB: car_market_database
      POSTGRES_USER: car_market_admin
      POSTGRES_PASSWORD: car_market_admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    networks:
      - auto_market_network

  auto-market-mongo:
    image: mongo:7.0
    restart: on-failure
    container_name: auto-market-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: car_market_admin
      MONGO_INITDB_ROOT_PASSWORD: car_market_admin
      MONGO_INITDB_DATABASE: car_market_db
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - auto_market_network

  auto-market-backend:
    build:
      context: ./back-end
    container_name: auto-market-backend
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - auto-market-postgres
      - auto-market-mongo
    networks:
      - auto_market_network

  auto-market-frontend:
    build:
      context: ./front-end
    container_name: auto-market-frontend
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - auto-market-backend
    networks:
      - auto_market_network
      
networks:
  auto_market_network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data: