spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/car_market_database
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  security:
    remember-me: "Remember-me-secret-key"
  mail:
    host: smtp.elasticemail.com
    port: 2525
    username: leheza.oleksii@gmail.com
    password: B69402AB00A3E28FA99E0377513A8A3E4F12
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true