spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/car_market_database
    username: ***********
    password: ***********
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  security:
    remember-me: ***********
  mail:
    host: smtp.elasticemail.com
    port: ***********
    username: ***********
    password: ***********
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true