spring:
  datasource:
    url: ***************
    username: ************
    password: ***************
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  security:
    remember-me: *****************
  mail:
    host: **************
    port: 2525
    username: ***************
    password: *********
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true